#!/usr/bin/python3
import tkinter as tk
import tkinter.ttk as ttk
import typing
import pygame
import pickle

# Mine logic
import MineSM as msm

# Input cards
import lib16inpind as ic


def play_click_sound():
    pygame.mixer.music.load("click.wav")
    pygame.mixer.music.play()

def play_boom_sound():
    pygame.mixer.music.load("boom.wav")
    pygame.mixer.music.play()


class MinefieldApp:
    def __init__(self, master=None):
        # build ui
        self.minewindow = tk.Tk() if master is None else tk.Toplevel(master)
        self.minewindow.configure(height=200, width=200)
        self.minewindow.title("Mines")
        notebook1 = ttk.Notebook(self.minewindow)
        notebook1.configure(height=400, width=400)
        frame1 = ttk.Frame(notebook1)
        frame1.configure(height=200, width=400)
        labelframe4 = ttk.Labelframe(frame1)
        labelframe4.configure(height=200, text='Button State', width=375)
        self.state1_1 = ttk.Checkbutton(labelframe4)
        self.stateval1_1 = tk.BooleanVar()
        self.state1_1.configure(variable=self.stateval1_1)
        self.state1_1.grid(column=1, row=1)
        self.state1_2 = ttk.Checkbutton(labelframe4)
        self.stateval1_2 = tk.BooleanVar()
        self.state1_2.configure(variable=self.stateval1_2)
        self.state1_2.grid(column=2, row=1)
        self.state1_3 = ttk.Checkbutton(labelframe4)
        self.stateval1_3 = tk.BooleanVar()
        self.state1_3.configure(variable=self.stateval1_3)
        self.state1_3.grid(column=3, row=1)
        self.state1_4 = ttk.Checkbutton(labelframe4)
        self.stateval1_4 = tk.BooleanVar()
        self.state1_4.configure(variable=self.stateval1_4)
        self.state1_4.grid(column=4, row=1)
        self.state1_5 = ttk.Checkbutton(labelframe4)
        self.stateval1_5 = tk.BooleanVar()
        self.state1_5.configure(variable=self.stateval1_5)
        self.state1_5.grid(column=5, row=1)
        self.state1_6 = ttk.Checkbutton(labelframe4)
        self.stateval1_6 = tk.BooleanVar()
        self.state1_6.configure(variable=self.stateval1_6)
        self.state1_6.grid(column=6, row=1)
        self.state1_7 = ttk.Checkbutton(labelframe4)
        self.stateval1_7 = tk.BooleanVar()
        self.state1_7.configure(variable=self.stateval1_7)
        self.state1_7.grid(column=7, row=1)
        self.state1_8 = ttk.Checkbutton(labelframe4)
        self.stateval1_8 = tk.BooleanVar()
        self.state1_8.configure(variable=self.stateval1_8)
        self.state1_8.grid(column=8, row=1)
        label1 = ttk.Label(labelframe4)
        label1.configure(text='P')
        label1.grid(column=1, row=0, sticky="w")
        label2 = ttk.Label(labelframe4)
        label2.configure(font="TkIconFont", text='Card 1')
        label2.grid(column=0, row=1)
        label3 = ttk.Label(labelframe4)
        label3.configure(text='Card 2')
        label3.grid(column=0, row=2)
        label4 = ttk.Label(labelframe4)
        label4.configure(text='Card 3')
        label4.grid(column=0, row=3)
        label5 = ttk.Label(labelframe4)
        label5.configure(text='Card 4')
        label5.grid(column=0, row=4)
        label6 = ttk.Label(labelframe4)
        label6.configure(text='Card 5')
        label6.grid(column=0, row=5)
        label7 = ttk.Label(labelframe4)
        label7.configure(text='Card 6')
        label7.grid(column=0, row=6)
        label8 = ttk.Label(labelframe4)
        label8.configure(text='Card 7')
        label8.grid(column=0, row=7)
        label9 = ttk.Label(labelframe4)
        label9.configure(text='Card 8')
        label9.grid(column=0, row=8)
        label12 = ttk.Label(labelframe4)
        label12.configure(relief="flat", state="normal", text='2')
        label12.grid(column=2, row=0, sticky="w")
        label13 = ttk.Label(labelframe4)
        label13.configure(text='3')
        label13.grid(column=3, row=0, sticky="w")
        label14 = ttk.Label(labelframe4)
        label14.configure(text='4')
        label14.grid(column=4, row=0, sticky="w")
        label15 = ttk.Label(labelframe4)
        label15.configure(text='5')
        label15.grid(column=5, row=0, sticky="w")
        label16 = ttk.Label(labelframe4)
        label16.configure(text='6')
        label16.grid(column=6, row=0, sticky="w")
        label17 = ttk.Label(labelframe4)
        label17.configure(text='7')
        label17.grid(column=7, row=0, sticky="w")
        label18 = ttk.Label(labelframe4)
        label18.configure(text='8')
        label18.grid(column=8, row=0, sticky="w")
        self.state2_1 = ttk.Checkbutton(labelframe4)
        self.stateval2_1 = tk.BooleanVar()
        self.state2_1.configure(variable=self.stateval2_1)
        self.state2_1.grid(column=1, row=2)
        self.state2_2 = ttk.Checkbutton(labelframe4)
        self.stateval2_2 = tk.BooleanVar()
        self.state2_2.configure(variable=self.stateval2_2)
        self.state2_2.grid(column=2, row=2)
        self.state2_3 = ttk.Checkbutton(labelframe4)
        self.stateval2_3 = tk.BooleanVar()
        self.state2_3.configure(variable=self.stateval2_3)
        self.state2_3.grid(column=3, row=2)
        self.state2_4 = ttk.Checkbutton(labelframe4)
        self.stateval2_4 = tk.BooleanVar()
        self.state2_4.configure(variable=self.stateval2_4)
        self.state2_4.grid(column=4, row=2)
        self.state2_5 = ttk.Checkbutton(labelframe4)
        self.stateval2_5 = tk.BooleanVar()
        self.state2_5.configure(variable=self.stateval2_5)
        self.state2_5.grid(column=5, row=2)
        self.state2_6 = ttk.Checkbutton(labelframe4)
        self.stateval2_6 = tk.BooleanVar()
        self.state2_6.configure(variable=self.stateval2_6)
        self.state2_6.grid(column=6, row=2)
        self.state2_7 = ttk.Checkbutton(labelframe4)
        self.stateval2_7 = tk.BooleanVar()
        self.state2_7.configure(variable=self.stateval2_7)
        self.state2_7.grid(column=7, row=2)
        self.state2_8 = ttk.Checkbutton(labelframe4)
        self.stateval2_8 = tk.BooleanVar()
        self.state2_8.configure(variable=self.stateval2_8)
        self.state2_8.grid(column=8, row=2)
        self.state3_1 = ttk.Checkbutton(labelframe4)
        self.stateval3_1 = tk.BooleanVar()
        self.state3_1.configure(variable=self.stateval3_1)
        self.state3_1.grid(column=1, row=3)
        self.state3_2 = ttk.Checkbutton(labelframe4)
        self.stateval3_2 = tk.BooleanVar()
        self.state3_2.configure(variable=self.stateval3_2)
        self.state3_2.grid(column=2, row=3)
        self.state3_3 = ttk.Checkbutton(labelframe4)
        self.stateval3_3 = tk.BooleanVar()
        self.state3_3.configure(variable=self.stateval3_3)
        self.state3_3.grid(column=3, row=3)
        self.state3_4 = ttk.Checkbutton(labelframe4)
        self.stateval3_4 = tk.BooleanVar()
        self.state3_4.configure(variable=self.stateval3_4)
        self.state3_4.grid(column=4, row=3)
        self.state3_5 = ttk.Checkbutton(labelframe4)
        self.stateval3_5 = tk.BooleanVar()
        self.state3_5.configure(variable=self.stateval3_5)
        self.state3_5.grid(column=5, row=3)
        self.state3_6 = ttk.Checkbutton(labelframe4)
        self.stateval3_6 = tk.BooleanVar()
        self.state3_6.configure(variable=self.stateval3_6)
        self.state3_6.grid(column=6, row=3)
        self.state3_7 = ttk.Checkbutton(labelframe4)
        self.stateval3_7 = tk.BooleanVar()
        self.state3_7.configure(variable=self.stateval3_7)
        self.state3_7.grid(column=7, row=3)
        self.state3_8 = ttk.Checkbutton(labelframe4)
        self.stateval3_8 = tk.BooleanVar()
        self.state3_8.configure(variable=self.stateval3_8)
        self.state3_8.grid(column=8, row=3)
        self.state4_1 = ttk.Checkbutton(labelframe4)
        self.stateval4_1 = tk.BooleanVar()
        self.state4_1.configure(variable=self.stateval4_1)
        self.state4_1.grid(column=1, row=4)
        self.state4_2 = ttk.Checkbutton(labelframe4)
        self.stateval4_2 = tk.BooleanVar()
        self.state4_2.configure(variable=self.stateval4_2)
        self.state4_2.grid(column=2, row=4)
        self.state4_3 = ttk.Checkbutton(labelframe4)
        self.stateval4_3 = tk.BooleanVar()
        self.state4_3.configure(variable=self.stateval4_3)
        self.state4_3.grid(column=3, row=4)
        self.state4_4 = ttk.Checkbutton(labelframe4)
        self.stateval4_4 = tk.BooleanVar()
        self.state4_4.configure(variable=self.stateval4_4)
        self.state4_4.grid(column=4, row=4)
        self.state4_5 = ttk.Checkbutton(labelframe4)
        self.stateval4_5 = tk.BooleanVar()
        self.state4_5.configure(variable=self.stateval4_5)
        self.state4_5.grid(column=5, row=4)
        self.state4_6 = ttk.Checkbutton(labelframe4)
        self.stateval4_6 = tk.BooleanVar()
        self.state4_6.configure(variable=self.stateval4_6)
        self.state4_6.grid(column=6, row=4)
        self.state4_7 = ttk.Checkbutton(labelframe4)
        self.stateval4_7 = tk.BooleanVar()
        self.state4_7.configure(variable=self.stateval4_7)
        self.state4_7.grid(column=7, row=4)
        self.state4_8 = ttk.Checkbutton(labelframe4)
        self.stateval4_8 = tk.BooleanVar()
        self.state4_8.configure(variable=self.stateval4_8)
        self.state4_8.grid(column=8, row=4)
        label10 = ttk.Label(labelframe4)
        label10.configure(text='9')
        label10.grid(column=9, row=0, sticky="w")
        label11 = ttk.Label(labelframe4)
        label11.configure(text='10')
        label11.grid(column=10, row=0, sticky="w")
        label19 = ttk.Label(labelframe4)
        label19.configure(text='11')
        label19.grid(column=11, row=0, sticky="w")
        label20 = ttk.Label(labelframe4)
        label20.configure(text='12')
        label20.grid(column=12, row=0, sticky="w")
        label21 = ttk.Label(labelframe4)
        label21.configure(text='13')
        label21.grid(column=13, row=0, sticky="w")
        label22 = ttk.Label(labelframe4)
        label22.configure(text='14')
        label22.grid(column=14, row=0, sticky="w")
        label23 = ttk.Label(labelframe4)
        label23.configure(text='15')
        label23.grid(column=15, row=0, sticky="w")
        label24 = ttk.Label(labelframe4)
        label24.configure(text='16')
        label24.grid(column=16, row=0, sticky="w")
        self.state1_9 = ttk.Checkbutton(labelframe4)
        self.stateval1_9 = tk.BooleanVar()
        self.state1_9.configure(variable=self.stateval1_9)
        self.state1_9.grid(column=9, row=1)
        self.state1_10 = ttk.Checkbutton(labelframe4)
        self.stateval1_10 = tk.BooleanVar()
        self.state1_10.configure(variable=self.stateval1_10)
        self.state1_10.grid(column=10, row=1)
        self.state1_11 = ttk.Checkbutton(labelframe4)
        self.stateval1_11 = tk.BooleanVar()
        self.state1_11.configure(variable=self.stateval1_11)
        self.state1_11.grid(column=11, row=1)
        self.state1_12 = ttk.Checkbutton(labelframe4)
        self.stateval1_12 = tk.BooleanVar()
        self.state1_12.configure(variable=self.stateval1_12)
        self.state1_12.grid(column=12, row=1)
        self.state1_13 = ttk.Checkbutton(labelframe4)
        self.stateval1_13 = tk.BooleanVar()
        self.state1_13.configure(variable=self.stateval1_13)
        self.state1_13.grid(column=13, row=1)
        self.state1_14 = ttk.Checkbutton(labelframe4)
        self.stateval1_14 = tk.BooleanVar()
        self.state1_14.configure(variable=self.stateval1_14)
        self.state1_14.grid(column=14, row=1)
        self.state1_15 = ttk.Checkbutton(labelframe4)
        self.stateval1_15 = tk.BooleanVar()
        self.state1_15.configure(variable=self.stateval1_15)
        self.state1_15.grid(column=15, row=1)
        self.state1_16 = ttk.Checkbutton(labelframe4)
        self.stateval1_16 = tk.BooleanVar()
        self.state1_16.configure(variable=self.stateval1_16)
        self.state1_16.grid(column=16, row=1)
        self.state2_9 = ttk.Checkbutton(labelframe4)
        self.stateval2_9 = tk.BooleanVar()
        self.state2_9.configure(variable=self.stateval2_9)
        self.state2_9.grid(column=9, row=2)
        self.state2_10 = ttk.Checkbutton(labelframe4)
        self.stateval2_10 = tk.BooleanVar()
        self.state2_10.configure(variable=self.stateval2_10)
        self.state2_10.grid(column=10, row=2)
        self.state2_11 = ttk.Checkbutton(labelframe4)
        self.stateval2_11 = tk.BooleanVar()
        self.state2_11.configure(variable=self.stateval2_11)
        self.state2_11.grid(column=11, row=2)
        self.state2_12 = ttk.Checkbutton(labelframe4)
        self.stateval2_12 = tk.BooleanVar()
        self.state2_12.configure(variable=self.stateval2_12)
        self.state2_12.grid(column=12, row=2)
        self.state2_13 = ttk.Checkbutton(labelframe4)
        self.stateval2_13 = tk.BooleanVar()
        self.state2_13.configure(variable=self.stateval2_13)
        self.state2_13.grid(column=13, row=2)
        self.state2_14 = ttk.Checkbutton(labelframe4)
        self.stateval2_14 = tk.BooleanVar()
        self.state2_14.configure(variable=self.stateval2_14)
        self.state2_14.grid(column=14, row=2)
        self.state2_15 = ttk.Checkbutton(labelframe4)
        self.stateval2_15 = tk.BooleanVar()
        self.state2_15.configure(variable=self.stateval2_15)
        self.state2_15.grid(column=15, row=2)
        self.state2_16 = ttk.Checkbutton(labelframe4)
        self.stateval2_16 = tk.BooleanVar()
        self.state2_16.configure(variable=self.stateval2_16)
        self.state2_16.grid(column=16, row=2)
        self.state3_9 = ttk.Checkbutton(labelframe4)
        self.stateval3_9 = tk.BooleanVar()
        self.state3_9.configure(variable=self.stateval3_9)
        self.state3_9.grid(column=9, row=3)
        self.state3_10 = ttk.Checkbutton(labelframe4)
        self.stateval3_10 = tk.BooleanVar()
        self.state3_10.configure(variable=self.stateval3_10)
        self.state3_10.grid(column=10, row=3)
        self.state3_11 = ttk.Checkbutton(labelframe4)
        self.stateval3_11 = tk.BooleanVar()
        self.state3_11.configure(variable=self.stateval3_11)
        self.state3_11.grid(column=11, row=3)
        self.state3_12 = ttk.Checkbutton(labelframe4)
        self.stateval3_12 = tk.BooleanVar()
        self.state3_12.configure(variable=self.stateval3_12)
        self.state3_12.grid(column=12, row=3)
        self.state3_13 = ttk.Checkbutton(labelframe4)
        self.stateval3_13 = tk.BooleanVar()
        self.state3_13.configure(variable=self.stateval3_13)
        self.state3_13.grid(column=13, row=3)
        self.state3_14 = ttk.Checkbutton(labelframe4)
        self.stateval3_14 = tk.BooleanVar()
        self.state3_14.configure(variable=self.stateval3_14)
        self.state3_14.grid(column=14, row=3)
        self.state3_15 = ttk.Checkbutton(labelframe4)
        self.stateval3_15 = tk.BooleanVar()
        self.state3_15.configure(variable=self.stateval3_15)
        self.state3_15.grid(column=15, row=3)
        self.state3_16 = ttk.Checkbutton(labelframe4)
        self.stateval3_16 = tk.BooleanVar()
        self.state3_16.configure(variable=self.stateval3_16)
        self.state3_16.grid(column=16, row=3)
        self.state4_9 = ttk.Checkbutton(labelframe4)
        self.stateval4_9 = tk.BooleanVar()
        self.state4_9.configure(variable=self.stateval4_9)
        self.state4_9.grid(column=9, row=4)
        self.state4_10 = ttk.Checkbutton(labelframe4)
        self.stateval4_10 = tk.BooleanVar()
        self.state4_10.configure(variable=self.stateval4_10)
        self.state4_10.grid(column=10, row=4)
        self.state4_11 = ttk.Checkbutton(labelframe4)
        self.stateval4_11 = tk.BooleanVar()
        self.state4_11.configure(variable=self.stateval4_11)
        self.state4_11.grid(column=11, row=4)
        self.state4_12 = ttk.Checkbutton(labelframe4)
        self.stateval4_12 = tk.BooleanVar()
        self.state4_12.configure(variable=self.stateval4_12)
        self.state4_12.grid(column=12, row=4)
        self.state4_13 = ttk.Checkbutton(labelframe4)
        self.stateval4_13 = tk.BooleanVar()
        self.state4_13.configure(variable=self.stateval4_13)
        self.state4_13.grid(column=13, row=4)
        self.state4_14 = ttk.Checkbutton(labelframe4)
        self.stateval4_14 = tk.BooleanVar()
        self.state4_14.configure(variable=self.stateval4_14)
        self.state4_14.grid(column=14, row=4)
        self.state4_15 = ttk.Checkbutton(labelframe4)
        self.stateval4_15 = tk.BooleanVar()
        self.state4_15.configure(variable=self.stateval4_15)
        self.state4_15.grid(column=15, row=4)
        self.state4_16 = ttk.Checkbutton(labelframe4)
        self.stateval4_16 = tk.BooleanVar()
        self.state4_16.configure(variable=self.stateval4_16)
        self.state4_16.grid(column=16, row=4)
        self.state5_1 = ttk.Checkbutton(labelframe4)
        self.stateval5_1 = tk.BooleanVar()
        self.state5_1.configure(variable=self.stateval5_1)
        self.state5_1.grid(column=1, row=5)
        self.state5_2 = ttk.Checkbutton(labelframe4)
        self.stateval5_2 = tk.BooleanVar()
        self.state5_2.configure(variable=self.stateval5_2)
        self.state5_2.grid(column=2, row=5)
        self.state5_3 = ttk.Checkbutton(labelframe4)
        self.stateval5_3 = tk.BooleanVar()
        self.state5_3.configure(variable=self.stateval5_3)
        self.state5_3.grid(column=3, row=5)
        self.state5_4 = ttk.Checkbutton(labelframe4)
        self.stateval5_4 = tk.BooleanVar()
        self.state5_4.configure(variable=self.stateval5_4)
        self.state5_4.grid(column=4, row=5)
        self.state5_5 = ttk.Checkbutton(labelframe4)
        self.stateval5_5 = tk.BooleanVar()
        self.state5_5.configure(variable=self.stateval5_5)
        self.state5_5.grid(column=5, row=5)
        self.state5_6 = ttk.Checkbutton(labelframe4)
        self.stateval5_6 = tk.BooleanVar()
        self.state5_6.configure(variable=self.stateval5_6)
        self.state5_6.grid(column=6, row=5)
        self.state5_7 = ttk.Checkbutton(labelframe4)
        self.stateval5_7 = tk.BooleanVar()
        self.state5_7.configure(variable=self.stateval5_7)
        self.state5_7.grid(column=7, row=5)
        self.state5_8 = ttk.Checkbutton(labelframe4)
        self.stateval5_8 = tk.BooleanVar()
        self.state5_8.configure(variable=self.stateval5_8)
        self.state5_8.grid(column=8, row=5)
        self.state6_1 = ttk.Checkbutton(labelframe4)
        self.stateval6_1 = tk.BooleanVar()
        self.state6_1.configure(variable=self.stateval6_1)
        self.state6_1.grid(column=1, row=6)
        self.state6_2 = ttk.Checkbutton(labelframe4)
        self.stateval6_2 = tk.BooleanVar()
        self.state6_2.configure(variable=self.stateval6_2)
        self.state6_2.grid(column=2, row=6)
        self.state6_3 = ttk.Checkbutton(labelframe4)
        self.stateval6_3 = tk.BooleanVar()
        self.state6_3.configure(variable=self.stateval6_3)
        self.state6_3.grid(column=3, row=6)
        self.state6_4 = ttk.Checkbutton(labelframe4)
        self.stateval6_4 = tk.BooleanVar()
        self.state6_4.configure(variable=self.stateval6_4)
        self.state6_4.grid(column=4, row=6)
        self.state6_5 = ttk.Checkbutton(labelframe4)
        self.stateval6_5 = tk.BooleanVar()
        self.state6_5.configure(variable=self.stateval6_5)
        self.state6_5.grid(column=5, row=6)
        self.state6_6 = ttk.Checkbutton(labelframe4)
        self.stateval6_6 = tk.BooleanVar()
        self.state6_6.configure(variable=self.stateval6_6)
        self.state6_6.grid(column=6, row=6)
        self.state6_7 = ttk.Checkbutton(labelframe4)
        self.stateval6_7 = tk.BooleanVar()
        self.state6_7.configure(variable=self.stateval6_7)
        self.state6_7.grid(column=7, row=6)
        self.state6_8 = ttk.Checkbutton(labelframe4)
        self.stateval6_8 = tk.BooleanVar()
        self.state6_8.configure(variable=self.stateval6_8)
        self.state6_8.grid(column=8, row=6)
        self.state7_1 = ttk.Checkbutton(labelframe4)
        self.stateval7_1 = tk.BooleanVar()
        self.state7_1.configure(variable=self.stateval7_1)
        self.state7_1.grid(column=1, row=7)
        self.state7_2 = ttk.Checkbutton(labelframe4)
        self.stateval7_2 = tk.BooleanVar()
        self.state7_2.configure(variable=self.stateval7_2)
        self.state7_2.grid(column=2, row=7)
        self.state7_3 = ttk.Checkbutton(labelframe4)
        self.stateval7_3 = tk.BooleanVar()
        self.state7_3.configure(variable=self.stateval7_3)
        self.state7_3.grid(column=3, row=7)
        self.state7_4 = ttk.Checkbutton(labelframe4)
        self.stateval7_4 = tk.BooleanVar()
        self.state7_4.configure(variable=self.stateval7_4)
        self.state7_4.grid(column=4, row=7)
        self.state7_5 = ttk.Checkbutton(labelframe4)
        self.stateval7_5 = tk.BooleanVar()
        self.state7_5.configure(variable=self.stateval7_5)
        self.state7_5.grid(column=5, row=7)
        self.state7_6 = ttk.Checkbutton(labelframe4)
        self.stateval7_6 = tk.BooleanVar()
        self.state7_6.configure(variable=self.stateval7_6)
        self.state7_6.grid(column=6, row=7)
        self.state7_7 = ttk.Checkbutton(labelframe4)
        self.stateval7_7 = tk.BooleanVar()
        self.state7_7.configure(variable=self.stateval7_7)
        self.state7_7.grid(column=7, row=7)
        self.state7_8 = ttk.Checkbutton(labelframe4)
        self.stateval7_8 = tk.BooleanVar()
        self.state7_8.configure(variable=self.stateval7_8)
        self.state7_8.grid(column=8, row=7)
        self.state8_1 = ttk.Checkbutton(labelframe4)
        self.stateval8_1 = tk.BooleanVar()
        self.state8_1.configure(variable=self.stateval8_1)
        self.state8_1.grid(column=1, row=8)
        self.state8_2 = ttk.Checkbutton(labelframe4)
        self.stateval8_2 = tk.BooleanVar()
        self.state8_2.configure(variable=self.stateval8_2)
        self.state8_2.grid(column=2, row=8)
        self.state8_3 = ttk.Checkbutton(labelframe4)
        self.stateval8_3 = tk.BooleanVar()
        self.state8_3.configure(variable=self.stateval8_3)
        self.state8_3.grid(column=3, row=8)
        self.state8_4 = ttk.Checkbutton(labelframe4)
        self.stateval8_4 = tk.BooleanVar()
        self.state8_4.configure(variable=self.stateval8_4)
        self.state8_4.grid(column=4, row=8)
        self.state8_5 = ttk.Checkbutton(labelframe4)
        self.stateval8_5 = tk.BooleanVar()
        self.state8_5.configure(variable=self.stateval8_5)
        self.state8_5.grid(column=5, row=8)
        self.state8_6 = ttk.Checkbutton(labelframe4)
        self.stateval8_6 = tk.BooleanVar()
        self.state8_6.configure(variable=self.stateval8_6)
        self.state8_6.grid(column=6, row=8)
        self.state8_7 = ttk.Checkbutton(labelframe4)
        self.stateval8_7 = tk.BooleanVar()
        self.state8_7.configure(variable=self.stateval8_7)
        self.state8_7.grid(column=7, row=8)
        self.state8_8 = ttk.Checkbutton(labelframe4)
        self.stateval8_8 = tk.BooleanVar()
        self.state8_8.configure(variable=self.stateval8_8)
        self.state8_8.grid(column=8, row=8)
        self.state5_9 = ttk.Checkbutton(labelframe4)
        self.stateval5_9 = tk.BooleanVar()
        self.state5_9.configure(variable=self.stateval5_9)
        self.state5_9.grid(column=9, row=5)
        self.state5_10 = ttk.Checkbutton(labelframe4)
        self.stateval5_10 = tk.BooleanVar()
        self.state5_10.configure(variable=self.stateval5_10)
        self.state5_10.grid(column=10, row=5)
        self.state5_11 = ttk.Checkbutton(labelframe4)
        self.stateval5_11 = tk.BooleanVar()
        self.state5_11.configure(variable=self.stateval5_11)
        self.state5_11.grid(column=11, row=5)
        self.state5_12 = ttk.Checkbutton(labelframe4)
        self.stateval5_12 = tk.BooleanVar()
        self.state5_12.configure(variable=self.stateval5_12)
        self.state5_12.grid(column=12, row=5)
        self.state5_13 = ttk.Checkbutton(labelframe4)
        self.stateval5_13 = tk.BooleanVar()
        self.state5_13.configure(variable=self.stateval5_13)
        self.state5_13.grid(column=13, row=5)
        self.state5_14 = ttk.Checkbutton(labelframe4)
        self.stateval5_14 = tk.BooleanVar()
        self.state5_14.configure(variable=self.stateval5_14)
        self.state5_14.grid(column=14, row=5)
        self.state5_15 = ttk.Checkbutton(labelframe4)
        self.stateval5_15 = tk.BooleanVar()
        self.state5_15.configure(variable=self.stateval5_15)
        self.state5_15.grid(column=15, row=5)
        self.state5_16 = ttk.Checkbutton(labelframe4)
        self.stateval5_16 = tk.BooleanVar()
        self.state5_16.configure(variable=self.stateval5_16)
        self.state5_16.grid(column=16, row=5)
        self.state6_9 = ttk.Checkbutton(labelframe4)
        self.stateval6_9 = tk.BooleanVar()
        self.state6_9.configure(variable=self.stateval6_9)
        self.state6_9.grid(column=9, row=6)
        self.state6_10 = ttk.Checkbutton(labelframe4)
        self.stateval6_10 = tk.BooleanVar()
        self.state6_10.configure(variable=self.stateval6_10)
        self.state6_10.grid(column=10, row=6)
        self.state6_11 = ttk.Checkbutton(labelframe4)
        self.stateval6_11 = tk.BooleanVar()
        self.state6_11.configure(variable=self.stateval6_11)
        self.state6_11.grid(column=11, row=6)
        self.state6_12 = ttk.Checkbutton(labelframe4)
        self.stateval6_12 = tk.BooleanVar()
        self.state6_12.configure(variable=self.stateval6_12)
        self.state6_12.grid(column=12, row=6)
        self.state6_13 = ttk.Checkbutton(labelframe4)
        self.stateval6_13 = tk.BooleanVar()
        self.state6_13.configure(variable=self.stateval6_13)
        self.state6_13.grid(column=13, row=6)
        self.state6_14 = ttk.Checkbutton(labelframe4)
        self.stateval6_14 = tk.BooleanVar()
        self.state6_14.configure(variable=self.stateval6_14)
        self.state6_14.grid(column=14, row=6)
        self.state6_15 = ttk.Checkbutton(labelframe4)
        self.stateval6_15 = tk.BooleanVar()
        self.state6_15.configure(variable=self.stateval6_15)
        self.state6_15.grid(column=15, row=6)
        self.state6_16 = ttk.Checkbutton(labelframe4)
        self.stateval6_16 = tk.BooleanVar()
        self.state6_16.configure(variable=self.stateval6_16)
        self.state6_16.grid(column=16, row=6)
        self.state7_9 = ttk.Checkbutton(labelframe4)
        self.stateval7_9 = tk.BooleanVar()
        self.state7_9.configure(variable=self.stateval7_9)
        self.state7_9.grid(column=9, row=7)
        self.state7_10 = ttk.Checkbutton(labelframe4)
        self.stateval7_10 = tk.BooleanVar()
        self.state7_10.configure(variable=self.stateval7_10)
        self.state7_10.grid(column=10, row=7)
        self.state7_11 = ttk.Checkbutton(labelframe4)
        self.stateval7_11 = tk.BooleanVar()
        self.state7_11.configure(variable=self.stateval7_11)
        self.state7_11.grid(column=11, row=7)
        self.state7_12 = ttk.Checkbutton(labelframe4)
        self.stateval7_12 = tk.BooleanVar()
        self.state7_12.configure(variable=self.stateval7_12)
        self.state7_12.grid(column=12, row=7)
        self.state7_13 = ttk.Checkbutton(labelframe4)
        self.stateval7_13 = tk.BooleanVar()
        self.state7_13.configure(variable=self.stateval7_13)
        self.state7_13.grid(column=13, row=7)
        self.state7_14 = ttk.Checkbutton(labelframe4)
        self.stateval7_14 = tk.BooleanVar()
        self.state7_14.configure(variable=self.stateval7_14)
        self.state7_14.grid(column=14, row=7)
        self.state7_15 = ttk.Checkbutton(labelframe4)
        self.stateval7_15 = tk.BooleanVar()
        self.state7_15.configure(variable=self.stateval7_15)
        self.state7_15.grid(column=15, row=7)
        self.state7_16 = ttk.Checkbutton(labelframe4)
        self.stateval7_16 = tk.BooleanVar()
        self.state7_16.configure(variable=self.stateval7_16)
        self.state7_16.grid(column=16, row=7)
        self.state8_9 = ttk.Checkbutton(labelframe4)
        self.stateval8_9 = tk.BooleanVar()
        self.state8_9.configure(variable=self.stateval8_9)
        self.state8_9.grid(column=9, row=8)
        self.state8_10 = ttk.Checkbutton(labelframe4)
        self.stateval8_10 = tk.BooleanVar()
        self.state8_10.configure(variable=self.stateval8_10)
        self.state8_10.grid(column=10, row=8)
        self.state8_11 = ttk.Checkbutton(labelframe4)
        self.stateval8_11 = tk.BooleanVar()
        self.state8_11.configure(variable=self.stateval8_11)
        self.state8_11.grid(column=11, row=8)
        self.state8_12 = ttk.Checkbutton(labelframe4)
        self.stateval8_12 = tk.BooleanVar()
        self.state8_12.configure(variable=self.stateval8_12)
        self.state8_12.grid(column=12, row=8)
        self.state8_13 = ttk.Checkbutton(labelframe4)
        self.stateval8_13 = tk.BooleanVar()
        self.state8_13.configure(variable=self.stateval8_13)
        self.state8_13.grid(column=13, row=8)
        self.state8_14 = ttk.Checkbutton(labelframe4)
        self.stateval8_14 = tk.BooleanVar()
        self.state8_14.configure(variable=self.stateval8_14)
        self.state8_14.grid(column=14, row=8)
        self.state8_15 = ttk.Checkbutton(labelframe4)
        self.stateval8_15 = tk.BooleanVar()
        self.state8_15.configure(variable=self.stateval8_15)
        self.state8_15.grid(column=15, row=8)
        self.state8_16 = ttk.Checkbutton(labelframe4)
        self.stateval8_16 = tk.BooleanVar()
        self.state8_16.configure(variable=self.stateval8_16)
        self.state8_16.grid(column=16, row=8)
        labelframe4.grid(column=0, ipadx=5, row=0)
        labelframe3 = ttk.Labelframe(frame1)
        labelframe3.configure(height=200, text='Manual Kill', width=200)
        self.btnClick = ttk.Button(labelframe3)
        self.btnClick.configure(text='Click')
        self.btnClick.grid(column=0, row=0)
        self.btnClick.configure(command=self.go_click)
        self.btnBoom = ttk.Button(labelframe3)
        self.btnBoom.configure(text='Boom')
        self.btnBoom.grid(column=1, padx=60, row=0)
        self.btnBoom.configure(command=self.go_boom)
        labelframe3.grid(column=0, ipady=5, pady=5, row=3)
        self.btnReset = ttk.Button(frame1)
        self.btnReset.configure(text='Reset Mine States')
        self.btnReset.grid(column=0, padx=40, pady=20, row=1, rowspan=2)
        self.btnReset.configure(command=self.reset_mine_states)
        frame1.grid(column=0, row=0)
        notebook1.add(frame1, text='Status')
        frame2 = ttk.Frame(notebook1)
        frame2.configure(height=200, width=200)
        labelframe1 = ttk.Labelframe(frame2)
        labelframe1.configure(height=200, text='Disable Input', width=200)
        self.disable1_1 = ttk.Checkbutton(labelframe1)
        self.disableval1_1 = tk.BooleanVar()
        self.disable1_1.configure(
            state="disabled",
            variable=self.disableval1_1)
        self.disable1_1.grid(column=1, row=1)
        self.disable1_1.configure(command=self.chkDisable_click)
        self.disable1_2 = ttk.Checkbutton(labelframe1)
        self.disableval1_2 = tk.BooleanVar()
        self.disable1_2.configure(variable=self.disableval1_2)
        self.disable1_2.grid(column=2, row=1)
        self.disable1_2.configure(command=self.chkDisable_click)
        self.disable1_3 = ttk.Checkbutton(labelframe1)
        self.disableval1_3 = tk.BooleanVar()
        self.disable1_3.configure(variable=self.disableval1_3)
        self.disable1_3.grid(column=3, row=1)
        self.disable1_3.configure(command=self.chkDisable_click)
        self.disable1_4 = ttk.Checkbutton(labelframe1)
        self.disableval1_4 = tk.BooleanVar()
        self.disable1_4.configure(variable=self.disableval1_4)
        self.disable1_4.grid(column=4, row=1)
        self.disable1_4.configure(command=self.chkDisable_click)
        self.disable1_5 = ttk.Checkbutton(labelframe1)
        self.disableval1_5 = tk.BooleanVar()
        self.disable1_5.configure(variable=self.disableval1_5)
        self.disable1_5.grid(column=5, row=1)
        self.disable1_5.configure(command=self.chkDisable_click)
        self.disable1_6 = ttk.Checkbutton(labelframe1)
        self.disableval1_6 = tk.BooleanVar()
        self.disable1_6.configure(variable=self.disableval1_6)
        self.disable1_6.grid(column=6, row=1)
        self.disable1_6.configure(command=self.chkDisable_click)
        self.disable1_7 = ttk.Checkbutton(labelframe1)
        self.disableval1_7 = tk.BooleanVar()
        self.disable1_7.configure(variable=self.disableval1_7)
        self.disable1_7.grid(column=7, row=1)
        self.disable1_7.configure(command=self.chkDisable_click)
        self.disable1_8 = ttk.Checkbutton(labelframe1)
        self.disableval1_8 = tk.BooleanVar()
        self.disable1_8.configure(variable=self.disableval1_8)
        self.disable1_8.grid(column=8, row=1)
        self.disable1_8.configure(command=self.chkDisable_click)
        label25 = ttk.Label(labelframe1)
        label25.configure(text='P')
        label25.grid(column=1, row=0, sticky="w")
        label26 = ttk.Label(labelframe1)
        label26.configure(font="TkIconFont", text='Card 1')
        label26.grid(column=0, row=1)
        label27 = ttk.Label(labelframe1)
        label27.configure(text='Card 2')
        label27.grid(column=0, row=2)
        label28 = ttk.Label(labelframe1)
        label28.configure(text='Card 3')
        label28.grid(column=0, row=3)
        label29 = ttk.Label(labelframe1)
        label29.configure(text='Card 4')
        label29.grid(column=0, row=4)
        label30 = ttk.Label(labelframe1)
        label30.configure(text='Card 5')
        label30.grid(column=0, row=5)
        label31 = ttk.Label(labelframe1)
        label31.configure(text='Card 6')
        label31.grid(column=0, row=6)
        label32 = ttk.Label(labelframe1)
        label32.configure(text='Card 7')
        label32.grid(column=0, row=7)
        label33 = ttk.Label(labelframe1)
        label33.configure(text='Card 8')
        label33.grid(column=0, row=8)
        label34 = ttk.Label(labelframe1)
        label34.configure(relief="flat", state="normal", text='2')
        label34.grid(column=2, row=0, sticky="w")
        label35 = ttk.Label(labelframe1)
        label35.configure(text='3')
        label35.grid(column=3, row=0, sticky="w")
        label36 = ttk.Label(labelframe1)
        label36.configure(text='4')
        label36.grid(column=4, row=0, sticky="w")
        label37 = ttk.Label(labelframe1)
        label37.configure(text='5')
        label37.grid(column=5, row=0, sticky="w")
        label38 = ttk.Label(labelframe1)
        label38.configure(text='6')
        label38.grid(column=6, row=0, sticky="w")
        label39 = ttk.Label(labelframe1)
        label39.configure(text='7')
        label39.grid(column=7, row=0, sticky="w")
        label40 = ttk.Label(labelframe1)
        label40.configure(text='8')
        label40.grid(column=8, row=0, sticky="w")
        self.disable2_1 = ttk.Checkbutton(labelframe1)
        self.disableval2_1 = tk.BooleanVar()
        self.disable2_1.configure(
            state="disabled",
            variable=self.disableval2_1)
        self.disable2_1.grid(column=1, row=2)
        self.disable2_1.configure(command=self.chkDisable_click)
        self.disable2_2 = ttk.Checkbutton(labelframe1)
        self.disableval2_2 = tk.BooleanVar()
        self.disable2_2.configure(variable=self.disableval2_2)
        self.disable2_2.grid(column=2, row=2)
        self.disable2_2.configure(command=self.chkDisable_click)
        self.disable2_3 = ttk.Checkbutton(labelframe1)
        self.disableval2_3 = tk.BooleanVar()
        self.disable2_3.configure(variable=self.disableval2_3)
        self.disable2_3.grid(column=3, row=2)
        self.disable2_3.configure(command=self.chkDisable_click)
        self.disable2_4 = ttk.Checkbutton(labelframe1)
        self.disableval2_4 = tk.BooleanVar()
        self.disable2_4.configure(variable=self.disableval2_4)
        self.disable2_4.grid(column=4, row=2)
        self.disable2_4.configure(command=self.chkDisable_click)
        self.disable2_5 = ttk.Checkbutton(labelframe1)
        self.disableval2_5 = tk.BooleanVar()
        self.disable2_5.configure(variable=self.disableval2_5)
        self.disable2_5.grid(column=5, row=2)
        self.disable2_5.configure(command=self.chkDisable_click)
        self.disable2_6 = ttk.Checkbutton(labelframe1)
        self.disableval2_6 = tk.BooleanVar()
        self.disable2_6.configure(variable=self.disableval2_6)
        self.disable2_6.grid(column=6, row=2)
        self.disable2_6.configure(command=self.chkDisable_click)
        self.disable2_7 = ttk.Checkbutton(labelframe1)
        self.disableval2_7 = tk.BooleanVar()
        self.disable2_7.configure(variable=self.disableval2_7)
        self.disable2_7.grid(column=7, row=2)
        self.disable2_7.configure(command=self.chkDisable_click)
        self.disable2_8 = ttk.Checkbutton(labelframe1)
        self.disableval2_8 = tk.BooleanVar()
        self.disable2_8.configure(variable=self.disableval2_8)
        self.disable2_8.grid(column=8, row=2)
        self.disable2_8.configure(command=self.chkDisable_click)
        self.disable3_1 = ttk.Checkbutton(labelframe1)
        self.disableval3_1 = tk.BooleanVar()
        self.disable3_1.configure(
            state="disabled",
            variable=self.disableval3_1)
        self.disable3_1.grid(column=1, row=3)
        self.disable3_1.configure(command=self.chkDisable_click)
        self.disable3_2 = ttk.Checkbutton(labelframe1)
        self.disableval3_2 = tk.BooleanVar()
        self.disable3_2.configure(variable=self.disableval3_2)
        self.disable3_2.grid(column=2, row=3)
        self.disable3_2.configure(command=self.chkDisable_click)
        self.disable3_3 = ttk.Checkbutton(labelframe1)
        self.disableval3_3 = tk.BooleanVar()
        self.disable3_3.configure(variable=self.disableval3_3)
        self.disable3_3.grid(column=3, row=3)
        self.disable3_3.configure(command=self.chkDisable_click)
        self.disable3_4 = ttk.Checkbutton(labelframe1)
        self.disableval3_4 = tk.BooleanVar()
        self.disable3_4.configure(variable=self.disableval3_4)
        self.disable3_4.grid(column=4, row=3)
        self.disable3_4.configure(command=self.chkDisable_click)
        self.disable3_5 = ttk.Checkbutton(labelframe1)
        self.disableval3_5 = tk.BooleanVar()
        self.disable3_5.configure(variable=self.disableval3_5)
        self.disable3_5.grid(column=5, row=3)
        self.disable3_5.configure(command=self.chkDisable_click)
        self.disable3_6 = ttk.Checkbutton(labelframe1)
        self.disableval3_6 = tk.BooleanVar()
        self.disable3_6.configure(variable=self.disableval3_6)
        self.disable3_6.grid(column=6, row=3)
        self.disable3_6.configure(command=self.chkDisable_click)
        self.disable3_7 = ttk.Checkbutton(labelframe1)
        self.disableval3_7 = tk.BooleanVar()
        self.disable3_7.configure(variable=self.disableval3_7)
        self.disable3_7.grid(column=7, row=3)
        self.disable3_7.configure(command=self.chkDisable_click)
        self.disable3_8 = ttk.Checkbutton(labelframe1)
        self.disableval3_8 = tk.BooleanVar()
        self.disable3_8.configure(variable=self.disableval3_8)
        self.disable3_8.grid(column=8, row=3)
        self.disable3_8.configure(command=self.chkDisable_click)
        self.disable4_1 = ttk.Checkbutton(labelframe1)
        self.disableval4_1 = tk.BooleanVar()
        self.disable4_1.configure(
            state="disabled",
            variable=self.disableval4_1)
        self.disable4_1.grid(column=1, row=4)
        self.disable4_1.configure(command=self.chkDisable_click)
        self.disable4_2 = ttk.Checkbutton(labelframe1)
        self.disableval4_2 = tk.BooleanVar()
        self.disable4_2.configure(variable=self.disableval4_2)
        self.disable4_2.grid(column=2, row=4)
        self.disable4_2.configure(command=self.chkDisable_click)
        self.disable4_3 = ttk.Checkbutton(labelframe1)
        self.disableval4_3 = tk.BooleanVar()
        self.disable4_3.configure(variable=self.disableval4_3)
        self.disable4_3.grid(column=3, row=4)
        self.disable4_3.configure(command=self.chkDisable_click)
        self.disable4_4 = ttk.Checkbutton(labelframe1)
        self.disableval4_4 = tk.BooleanVar()
        self.disable4_4.configure(variable=self.disableval4_4)
        self.disable4_4.grid(column=4, row=4)
        self.disable4_4.configure(command=self.chkDisable_click)
        self.disable4_5 = ttk.Checkbutton(labelframe1)
        self.disableval4_5 = tk.BooleanVar()
        self.disable4_5.configure(variable=self.disableval4_5)
        self.disable4_5.grid(column=5, row=4)
        self.disable4_5.configure(command=self.chkDisable_click)
        self.disable4_6 = ttk.Checkbutton(labelframe1)
        self.disableval4_6 = tk.BooleanVar()
        self.disable4_6.configure(variable=self.disableval4_6)
        self.disable4_6.grid(column=6, row=4)
        self.disable4_6.configure(command=self.chkDisable_click)
        self.disable4_7 = ttk.Checkbutton(labelframe1)
        self.disableval4_7 = tk.BooleanVar()
        self.disable4_7.configure(variable=self.disableval4_7)
        self.disable4_7.grid(column=7, row=4)
        self.disable4_7.configure(command=self.chkDisable_click)
        self.disable4_8 = ttk.Checkbutton(labelframe1)
        self.disableval4_8 = tk.BooleanVar()
        self.disable4_8.configure(variable=self.disableval4_8)
        self.disable4_8.grid(column=8, row=4)
        self.disable4_8.configure(command=self.chkDisable_click)
        label41 = ttk.Label(labelframe1)
        label41.configure(text='9')
        label41.grid(column=9, row=0, sticky="w")
        label42 = ttk.Label(labelframe1)
        label42.configure(text='10')
        label42.grid(column=10, row=0, sticky="w")
        label43 = ttk.Label(labelframe1)
        label43.configure(text='11')
        label43.grid(column=11, row=0, sticky="w")
        label44 = ttk.Label(labelframe1)
        label44.configure(text='12')
        label44.grid(column=12, row=0, sticky="w")
        label45 = ttk.Label(labelframe1)
        label45.configure(text='13')
        label45.grid(column=13, row=0, sticky="w")
        label46 = ttk.Label(labelframe1)
        label46.configure(text='14')
        label46.grid(column=14, row=0, sticky="w")
        label47 = ttk.Label(labelframe1)
        label47.configure(text='15')
        label47.grid(column=15, row=0, sticky="w")
        label48 = ttk.Label(labelframe1)
        label48.configure(text='16')
        label48.grid(column=16, row=0, sticky="w")
        self.disable1_9 = ttk.Checkbutton(labelframe1)
        self.disableval1_9 = tk.BooleanVar()
        self.disable1_9.configure(variable=self.disableval1_9)
        self.disable1_9.grid(column=9, row=1)
        self.disable1_9.configure(command=self.chkDisable_click)
        self.disable1_10 = ttk.Checkbutton(labelframe1)
        self.disableval1_10 = tk.BooleanVar()
        self.disable1_10.configure(variable=self.disableval1_10)
        self.disable1_10.grid(column=10, row=1)
        self.disable1_10.configure(command=self.chkDisable_click)
        self.disable1_11 = ttk.Checkbutton(labelframe1)
        self.disableval1_11 = tk.BooleanVar()
        self.disable1_11.configure(variable=self.disableval1_11)
        self.disable1_11.grid(column=11, row=1)
        self.disable1_11.configure(command=self.chkDisable_click)
        self.disable1_12 = ttk.Checkbutton(labelframe1)
        self.disableval1_12 = tk.BooleanVar()
        self.disable1_12.configure(variable=self.disableval1_12)
        self.disable1_12.grid(column=12, row=1)
        self.disable1_12.configure(command=self.chkDisable_click)
        self.disable1_13 = ttk.Checkbutton(labelframe1)
        self.disableval1_13 = tk.BooleanVar()
        self.disable1_13.configure(variable=self.disableval1_13)
        self.disable1_13.grid(column=13, row=1)
        self.disable1_13.configure(command=self.chkDisable_click)
        self.disable1_14 = ttk.Checkbutton(labelframe1)
        self.disableval1_14 = tk.BooleanVar()
        self.disable1_14.configure(variable=self.disableval1_14)
        self.disable1_14.grid(column=14, row=1)
        self.disable1_14.configure(command=self.chkDisable_click)
        self.disable1_15 = ttk.Checkbutton(labelframe1)
        self.disableval1_15 = tk.BooleanVar()
        self.disable1_15.configure(variable=self.disableval1_15)
        self.disable1_15.grid(column=15, row=1)
        self.disable1_15.configure(command=self.chkDisable_click)
        self.disable1_16 = ttk.Checkbutton(labelframe1)
        self.disableval1_16 = tk.BooleanVar()
        self.disable1_16.configure(variable=self.disableval1_16)
        self.disable1_16.grid(column=16, row=1)
        self.disable1_16.configure(command=self.chkDisable_click)
        self.disable2_9 = ttk.Checkbutton(labelframe1)
        self.disableval2_9 = tk.BooleanVar()
        self.disable2_9.configure(variable=self.disableval2_9)
        self.disable2_9.grid(column=9, row=2)
        self.disable2_9.configure(command=self.chkDisable_click)
        self.disable2_10 = ttk.Checkbutton(labelframe1)
        self.disableval2_10 = tk.BooleanVar()
        self.disable2_10.configure(variable=self.disableval2_10)
        self.disable2_10.grid(column=10, row=2)
        self.disable2_10.configure(command=self.chkDisable_click)
        self.disable2_11 = ttk.Checkbutton(labelframe1)
        self.disableval2_11 = tk.BooleanVar()
        self.disable2_11.configure(variable=self.disableval2_11)
        self.disable2_11.grid(column=11, row=2)
        self.disable2_11.configure(command=self.chkDisable_click)
        self.disable2_12 = ttk.Checkbutton(labelframe1)
        self.disableval2_12 = tk.BooleanVar()
        self.disable2_12.configure(variable=self.disableval2_12)
        self.disable2_12.grid(column=12, row=2)
        self.disable2_12.configure(command=self.chkDisable_click)
        self.disable2_13 = ttk.Checkbutton(labelframe1)
        self.disableval2_13 = tk.BooleanVar()
        self.disable2_13.configure(variable=self.disableval2_13)
        self.disable2_13.grid(column=13, row=2)
        self.disable2_13.configure(command=self.chkDisable_click)
        self.disable2_14 = ttk.Checkbutton(labelframe1)
        self.disableval2_14 = tk.BooleanVar()
        self.disable2_14.configure(variable=self.disableval2_14)
        self.disable2_14.grid(column=14, row=2)
        self.disable2_14.configure(command=self.chkDisable_click)
        self.disable2_15 = ttk.Checkbutton(labelframe1)
        self.disableval2_15 = tk.BooleanVar()
        self.disable2_15.configure(variable=self.disableval2_15)
        self.disable2_15.grid(column=15, row=2)
        self.disable2_15.configure(command=self.chkDisable_click)
        self.disable2_16 = ttk.Checkbutton(labelframe1)
        self.disableval2_16 = tk.BooleanVar()
        self.disable2_16.configure(variable=self.disableval2_16)
        self.disable2_16.grid(column=16, row=2)
        self.disable2_16.configure(command=self.chkDisable_click)
        self.disable3_9 = ttk.Checkbutton(labelframe1)
        self.disableval3_9 = tk.BooleanVar()
        self.disable3_9.configure(variable=self.disableval3_9)
        self.disable3_9.grid(column=9, row=3)
        self.disable3_9.configure(command=self.chkDisable_click)
        self.disable3_10 = ttk.Checkbutton(labelframe1)
        self.disableval3_10 = tk.BooleanVar()
        self.disable3_10.configure(variable=self.disableval3_10)
        self.disable3_10.grid(column=10, row=3)
        self.disable3_10.configure(command=self.chkDisable_click)
        self.disable3_11 = ttk.Checkbutton(labelframe1)
        self.disableval3_11 = tk.BooleanVar()
        self.disable3_11.configure(variable=self.disableval3_11)
        self.disable3_11.grid(column=11, row=3)
        self.disable3_11.configure(command=self.chkDisable_click)
        self.disable3_12 = ttk.Checkbutton(labelframe1)
        self.disableval3_12 = tk.BooleanVar()
        self.disable3_12.configure(variable=self.disableval3_12)
        self.disable3_12.grid(column=12, row=3)
        self.disable3_12.configure(command=self.chkDisable_click)
        self.disable3_13 = ttk.Checkbutton(labelframe1)
        self.disableval3_13 = tk.BooleanVar()
        self.disable3_13.configure(variable=self.disableval3_13)
        self.disable3_13.grid(column=13, row=3)
        self.disable3_13.configure(command=self.chkDisable_click)
        self.disable3_14 = ttk.Checkbutton(labelframe1)
        self.disableval3_14 = tk.BooleanVar()
        self.disable3_14.configure(variable=self.disableval3_14)
        self.disable3_14.grid(column=14, row=3)
        self.disable3_14.configure(command=self.chkDisable_click)
        self.disable3_15 = ttk.Checkbutton(labelframe1)
        self.disableval3_15 = tk.BooleanVar()
        self.disable3_15.configure(variable=self.disableval3_15)
        self.disable3_15.grid(column=15, row=3)
        self.disable3_15.configure(command=self.chkDisable_click)
        self.disable3_16 = ttk.Checkbutton(labelframe1)
        self.disableval3_16 = tk.BooleanVar()
        self.disable3_16.configure(variable=self.disableval3_16)
        self.disable3_16.grid(column=16, row=3)
        self.disable3_16.configure(command=self.chkDisable_click)
        self.disable4_9 = ttk.Checkbutton(labelframe1)
        self.disableval4_9 = tk.BooleanVar()
        self.disable4_9.configure(variable=self.disableval4_9)
        self.disable4_9.grid(column=9, row=4)
        self.disable4_9.configure(command=self.chkDisable_click)
        self.disable4_10 = ttk.Checkbutton(labelframe1)
        self.disableval4_10 = tk.BooleanVar()
        self.disable4_10.configure(variable=self.disableval4_10)
        self.disable4_10.grid(column=10, row=4)
        self.disable4_10.configure(command=self.chkDisable_click)
        self.disable4_11 = ttk.Checkbutton(labelframe1)
        self.disableval4_11 = tk.BooleanVar()
        self.disable4_11.configure(variable=self.disableval4_11)
        self.disable4_11.grid(column=11, row=4)
        self.disable4_11.configure(command=self.chkDisable_click)
        self.disable4_12 = ttk.Checkbutton(labelframe1)
        self.disableval4_12 = tk.BooleanVar()
        self.disable4_12.configure(variable=self.disableval4_12)
        self.disable4_12.grid(column=12, row=4)
        self.disable4_12.configure(command=self.chkDisable_click)
        self.disable4_13 = ttk.Checkbutton(labelframe1)
        self.disableval4_13 = tk.BooleanVar()
        self.disable4_13.configure(variable=self.disableval4_13)
        self.disable4_13.grid(column=13, row=4)
        self.disable4_13.configure(command=self.chkDisable_click)
        self.disable4_14 = ttk.Checkbutton(labelframe1)
        self.disableval4_14 = tk.BooleanVar()
        self.disable4_14.configure(variable=self.disableval4_14)
        self.disable4_14.grid(column=14, row=4)
        self.disable4_14.configure(command=self.chkDisable_click)
        self.disable4_15 = ttk.Checkbutton(labelframe1)
        self.disableval4_15 = tk.BooleanVar()
        self.disable4_15.configure(variable=self.disableval4_15)
        self.disable4_15.grid(column=15, row=4)
        self.disable4_15.configure(command=self.chkDisable_click)
        self.disable4_16 = ttk.Checkbutton(labelframe1)
        self.disableval4_16 = tk.BooleanVar()
        self.disable4_16.configure(variable=self.disableval4_16)
        self.disable4_16.grid(column=16, row=4)
        self.disable4_16.configure(command=self.chkDisable_click)
        self.disable5_1 = ttk.Checkbutton(labelframe1)
        self.disableval5_1 = tk.BooleanVar()
        self.disable5_1.configure(
            state="disabled",
            variable=self.disableval5_1)
        self.disable5_1.grid(column=1, row=5)
        self.disable5_1.configure(command=self.chkDisable_click)
        self.disable5_2 = ttk.Checkbutton(labelframe1)
        self.disableval5_2 = tk.BooleanVar()
        self.disable5_2.configure(variable=self.disableval5_2)
        self.disable5_2.grid(column=2, row=5)
        self.disable5_2.configure(command=self.chkDisable_click)
        self.disable5_3 = ttk.Checkbutton(labelframe1)
        self.disableval5_3 = tk.BooleanVar()
        self.disable5_3.configure(variable=self.disableval5_3)
        self.disable5_3.grid(column=3, row=5)
        self.disable5_3.configure(command=self.chkDisable_click)
        self.disable5_4 = ttk.Checkbutton(labelframe1)
        self.disableval5_4 = tk.BooleanVar()
        self.disable5_4.configure(variable=self.disableval5_4)
        self.disable5_4.grid(column=4, row=5)
        self.disable5_4.configure(command=self.chkDisable_click)
        self.disable5_5 = ttk.Checkbutton(labelframe1)
        self.disableval5_5 = tk.BooleanVar()
        self.disable5_5.configure(variable=self.disableval5_5)
        self.disable5_5.grid(column=5, row=5)
        self.disable5_5.configure(command=self.chkDisable_click)
        self.disable5_6 = ttk.Checkbutton(labelframe1)
        self.disableval5_6 = tk.BooleanVar()
        self.disable5_6.configure(variable=self.disableval5_6)
        self.disable5_6.grid(column=6, row=5)
        self.disable5_6.configure(command=self.chkDisable_click)
        self.disable5_7 = ttk.Checkbutton(labelframe1)
        self.disableval5_7 = tk.BooleanVar()
        self.disable5_7.configure(variable=self.disableval5_7)
        self.disable5_7.grid(column=7, row=5)
        self.disable5_7.configure(command=self.chkDisable_click)
        self.disable5_8 = ttk.Checkbutton(labelframe1)
        self.disableval5_8 = tk.BooleanVar()
        self.disable5_8.configure(variable=self.disableval5_8)
        self.disable5_8.grid(column=8, row=5)
        self.disable5_8.configure(command=self.chkDisable_click)
        self.disable6_1 = ttk.Checkbutton(labelframe1)
        self.disableval6_1 = tk.BooleanVar()
        self.disable6_1.configure(
            state="disabled",
            variable=self.disableval6_1)
        self.disable6_1.grid(column=1, row=6)
        self.disable6_1.configure(command=self.chkDisable_click)
        self.disable6_2 = ttk.Checkbutton(labelframe1)
        self.disableval6_2 = tk.BooleanVar()
        self.disable6_2.configure(variable=self.disableval6_2)
        self.disable6_2.grid(column=2, row=6)
        self.disable6_2.configure(command=self.chkDisable_click)
        self.disable6_3 = ttk.Checkbutton(labelframe1)
        self.disableval6_3 = tk.BooleanVar()
        self.disable6_3.configure(variable=self.disableval6_3)
        self.disable6_3.grid(column=3, row=6)
        self.disable6_3.configure(command=self.chkDisable_click)
        self.disable6_4 = ttk.Checkbutton(labelframe1)
        self.disableval6_4 = tk.BooleanVar()
        self.disable6_4.configure(variable=self.disableval6_4)
        self.disable6_4.grid(column=4, row=6)
        self.disable6_4.configure(command=self.chkDisable_click)
        self.disable6_5 = ttk.Checkbutton(labelframe1)
        self.disableval6_5 = tk.BooleanVar()
        self.disable6_5.configure(variable=self.disableval6_5)
        self.disable6_5.grid(column=5, row=6)
        self.disable6_5.configure(command=self.chkDisable_click)
        self.disable6_6 = ttk.Checkbutton(labelframe1)
        self.disableval6_6 = tk.BooleanVar()
        self.disable6_6.configure(variable=self.disableval6_6)
        self.disable6_6.grid(column=6, row=6)
        self.disable6_6.configure(command=self.chkDisable_click)
        self.disable6_7 = ttk.Checkbutton(labelframe1)
        self.disableval6_7 = tk.BooleanVar()
        self.disable6_7.configure(variable=self.disableval6_7)
        self.disable6_7.grid(column=7, row=6)
        self.disable6_7.configure(command=self.chkDisable_click)
        self.disable6_8 = ttk.Checkbutton(labelframe1)
        self.disableval6_8 = tk.BooleanVar()
        self.disable6_8.configure(variable=self.disableval6_8)
        self.disable6_8.grid(column=8, row=6)
        self.disable6_8.configure(command=self.chkDisable_click)
        self.disable7_1 = ttk.Checkbutton(labelframe1)
        self.disableval7_1 = tk.BooleanVar()
        self.disable7_1.configure(
            state="disabled",
            variable=self.disableval7_1)
        self.disable7_1.grid(column=1, row=7)
        self.disable7_1.configure(command=self.chkDisable_click)
        self.disable7_2 = ttk.Checkbutton(labelframe1)
        self.disableval7_2 = tk.BooleanVar()
        self.disable7_2.configure(variable=self.disableval7_2)
        self.disable7_2.grid(column=2, row=7)
        self.disable7_2.configure(command=self.chkDisable_click)
        self.disable7_3 = ttk.Checkbutton(labelframe1)
        self.disableval7_3 = tk.BooleanVar()
        self.disable7_3.configure(variable=self.disableval7_3)
        self.disable7_3.grid(column=3, row=7)
        self.disable7_3.configure(command=self.chkDisable_click)
        self.disable7_4 = ttk.Checkbutton(labelframe1)
        self.disableval7_4 = tk.BooleanVar()
        self.disable7_4.configure(variable=self.disableval7_4)
        self.disable7_4.grid(column=4, row=7)
        self.disable7_4.configure(command=self.chkDisable_click)
        self.disable7_5 = ttk.Checkbutton(labelframe1)
        self.disableval7_5 = tk.BooleanVar()
        self.disable7_5.configure(variable=self.disableval7_5)
        self.disable7_5.grid(column=5, row=7)
        self.disable7_5.configure(command=self.chkDisable_click)
        self.disable7_6 = ttk.Checkbutton(labelframe1)
        self.disableval7_6 = tk.BooleanVar()
        self.disable7_6.configure(variable=self.disableval7_6)
        self.disable7_6.grid(column=6, row=7)
        self.disable7_6.configure(command=self.chkDisable_click)
        self.disable7_7 = ttk.Checkbutton(labelframe1)
        self.disableval7_7 = tk.BooleanVar()
        self.disable7_7.configure(variable=self.disableval7_7)
        self.disable7_7.grid(column=7, row=7)
        self.disable7_7.configure(command=self.chkDisable_click)
        self.disable7_8 = ttk.Checkbutton(labelframe1)
        self.disableval7_8 = tk.BooleanVar()
        self.disable7_8.configure(variable=self.disableval7_8)
        self.disable7_8.grid(column=8, row=7)
        self.disable7_8.configure(command=self.chkDisable_click)
        self.disable8_1 = ttk.Checkbutton(labelframe1)
        self.disableval8_1 = tk.BooleanVar()
        self.disable8_1.configure(
            state="disabled",
            variable=self.disableval8_1)
        self.disable8_1.grid(column=1, row=8)
        self.disable8_1.configure(command=self.chkDisable_click)
        self.disable8_2 = ttk.Checkbutton(labelframe1)
        self.disableval8_2 = tk.BooleanVar()
        self.disable8_2.configure(variable=self.disableval8_2)
        self.disable8_2.grid(column=2, row=8)
        self.disable8_2.configure(command=self.chkDisable_click)
        self.disable8_3 = ttk.Checkbutton(labelframe1)
        self.disableval8_3 = tk.BooleanVar()
        self.disable8_3.configure(variable=self.disableval8_3)
        self.disable8_3.grid(column=3, row=8)
        self.disable8_3.configure(command=self.chkDisable_click)
        self.disable8_4 = ttk.Checkbutton(labelframe1)
        self.disableval8_4 = tk.BooleanVar()
        self.disable8_4.configure(variable=self.disableval8_4)
        self.disable8_4.grid(column=4, row=8)
        self.disable8_4.configure(command=self.chkDisable_click)
        self.disable8_5 = ttk.Checkbutton(labelframe1)
        self.disableval8_5 = tk.BooleanVar()
        self.disable8_5.configure(variable=self.disableval8_5)
        self.disable8_5.grid(column=5, row=8)
        self.disable8_5.configure(command=self.chkDisable_click)
        self.disable8_6 = ttk.Checkbutton(labelframe1)
        self.disableval8_6 = tk.BooleanVar()
        self.disable8_6.configure(variable=self.disableval8_6)
        self.disable8_6.grid(column=6, row=8)
        self.disable8_6.configure(command=self.chkDisable_click)
        self.disable8_7 = ttk.Checkbutton(labelframe1)
        self.disableval8_7 = tk.BooleanVar()
        self.disable8_7.configure(variable=self.disableval8_7)
        self.disable8_7.grid(column=7, row=8)
        self.disable8_7.configure(command=self.chkDisable_click)
        self.disable8_8 = ttk.Checkbutton(labelframe1)
        self.disableval8_8 = tk.BooleanVar()
        self.disable8_8.configure(variable=self.disableval8_8)
        self.disable8_8.grid(column=8, row=8)
        self.disable8_8.configure(command=self.chkDisable_click)
        self.disable5_9 = ttk.Checkbutton(labelframe1)
        self.disableval5_9 = tk.BooleanVar()
        self.disable5_9.configure(variable=self.disableval5_9)
        self.disable5_9.grid(column=9, row=5)
        self.disable5_9.configure(command=self.chkDisable_click)
        self.disable5_10 = ttk.Checkbutton(labelframe1)
        self.disableval5_10 = tk.BooleanVar()
        self.disable5_10.configure(variable=self.disableval5_10)
        self.disable5_10.grid(column=10, row=5)
        self.disable5_10.configure(command=self.chkDisable_click)
        self.disable5_11 = ttk.Checkbutton(labelframe1)
        self.disableval5_11 = tk.BooleanVar()
        self.disable5_11.configure(variable=self.disableval5_11)
        self.disable5_11.grid(column=11, row=5)
        self.disable5_11.configure(command=self.chkDisable_click)
        self.disable5_12 = ttk.Checkbutton(labelframe1)
        self.disableval5_12 = tk.BooleanVar()
        self.disable5_12.configure(variable=self.disableval5_12)
        self.disable5_12.grid(column=12, row=5)
        self.disable5_12.configure(command=self.chkDisable_click)
        self.disable5_13 = ttk.Checkbutton(labelframe1)
        self.disableval5_13 = tk.BooleanVar()
        self.disable5_13.configure(variable=self.disableval5_13)
        self.disable5_13.grid(column=13, row=5)
        self.disable5_13.configure(command=self.chkDisable_click)
        self.disable5_14 = ttk.Checkbutton(labelframe1)
        self.disableval5_14 = tk.BooleanVar()
        self.disable5_14.configure(variable=self.disableval5_14)
        self.disable5_14.grid(column=14, row=5)
        self.disable5_14.configure(command=self.chkDisable_click)
        self.disable5_15 = ttk.Checkbutton(labelframe1)
        self.disableval5_15 = tk.BooleanVar()
        self.disable5_15.configure(variable=self.disableval5_15)
        self.disable5_15.grid(column=15, row=5)
        self.disable5_15.configure(command=self.chkDisable_click)
        self.disable5_16 = ttk.Checkbutton(labelframe1)
        self.disableval5_16 = tk.BooleanVar()
        self.disable5_16.configure(variable=self.disableval5_16)
        self.disable5_16.grid(column=16, row=5)
        self.disable5_16.configure(command=self.chkDisable_click)
        self.disable6_9 = ttk.Checkbutton(labelframe1)
        self.disableval6_9 = tk.BooleanVar()
        self.disable6_9.configure(variable=self.disableval6_9)
        self.disable6_9.grid(column=9, row=6)
        self.disable6_9.configure(command=self.chkDisable_click)
        self.disable6_10 = ttk.Checkbutton(labelframe1)
        self.disableval6_10 = tk.BooleanVar()
        self.disable6_10.configure(variable=self.disableval6_10)
        self.disable6_10.grid(column=10, row=6)
        self.disable6_10.configure(command=self.chkDisable_click)
        self.disable6_11 = ttk.Checkbutton(labelframe1)
        self.disableval6_11 = tk.BooleanVar()
        self.disable6_11.configure(variable=self.disableval6_11)
        self.disable6_11.grid(column=11, row=6)
        self.disable6_11.configure(command=self.chkDisable_click)
        self.disable6_12 = ttk.Checkbutton(labelframe1)
        self.disableval6_12 = tk.BooleanVar()
        self.disable6_12.configure(variable=self.disableval6_12)
        self.disable6_12.grid(column=12, row=6)
        self.disable6_12.configure(command=self.chkDisable_click)
        self.disable6_13 = ttk.Checkbutton(labelframe1)
        self.disableval6_13 = tk.BooleanVar()
        self.disable6_13.configure(variable=self.disableval6_13)
        self.disable6_13.grid(column=13, row=6)
        self.disable6_13.configure(command=self.chkDisable_click)
        self.disable6_14 = ttk.Checkbutton(labelframe1)
        self.disableval6_14 = tk.BooleanVar()
        self.disable6_14.configure(variable=self.disableval6_14)
        self.disable6_14.grid(column=14, row=6)
        self.disable6_14.configure(command=self.chkDisable_click)
        self.disable6_15 = ttk.Checkbutton(labelframe1)
        self.disableval6_15 = tk.BooleanVar()
        self.disable6_15.configure(variable=self.disableval6_15)
        self.disable6_15.grid(column=15, row=6)
        self.disable6_15.configure(command=self.chkDisable_click)
        self.disable6_16 = ttk.Checkbutton(labelframe1)
        self.disableval6_16 = tk.BooleanVar()
        self.disable6_16.configure(variable=self.disableval6_16)
        self.disable6_16.grid(column=16, row=6)
        self.disable6_16.configure(command=self.chkDisable_click)
        self.disable7_9 = ttk.Checkbutton(labelframe1)
        self.disableval7_9 = tk.BooleanVar()
        self.disable7_9.configure(variable=self.disableval7_9)
        self.disable7_9.grid(column=9, row=7)
        self.disable7_9.configure(command=self.chkDisable_click)
        self.disable7_10 = ttk.Checkbutton(labelframe1)
        self.disableval7_10 = tk.BooleanVar()
        self.disable7_10.configure(variable=self.disableval7_10)
        self.disable7_10.grid(column=10, row=7)
        self.disable7_10.configure(command=self.chkDisable_click)
        self.disable7_11 = ttk.Checkbutton(labelframe1)
        self.disableval7_11 = tk.BooleanVar()
        self.disable7_11.configure(variable=self.disableval7_11)
        self.disable7_11.grid(column=11, row=7)
        self.disable7_11.configure(command=self.chkDisable_click)
        self.disable7_12 = ttk.Checkbutton(labelframe1)
        self.disableval7_12 = tk.BooleanVar()
        self.disable7_12.configure(variable=self.disableval7_12)
        self.disable7_12.grid(column=12, row=7)
        self.disable7_12.configure(command=self.chkDisable_click)
        self.disable7_13 = ttk.Checkbutton(labelframe1)
        self.disableval7_13 = tk.BooleanVar()
        self.disable7_13.configure(variable=self.disableval7_13)
        self.disable7_13.grid(column=13, row=7)
        self.disable7_13.configure(command=self.chkDisable_click)
        self.disable7_14 = ttk.Checkbutton(labelframe1)
        self.disableval7_14 = tk.BooleanVar()
        self.disable7_14.configure(variable=self.disableval7_14)
        self.disable7_14.grid(column=14, row=7)
        self.disable7_14.configure(command=self.chkDisable_click)
        self.disable7_15 = ttk.Checkbutton(labelframe1)
        self.disableval7_15 = tk.BooleanVar()
        self.disable7_15.configure(variable=self.disableval7_15)
        self.disable7_15.grid(column=15, row=7)
        self.disable7_15.configure(command=self.chkDisable_click)
        self.disable7_16 = ttk.Checkbutton(labelframe1)
        self.disableval7_16 = tk.BooleanVar()
        self.disable7_16.configure(variable=self.disableval7_16)
        self.disable7_16.grid(column=16, row=7)
        self.disable7_16.configure(command=self.chkDisable_click)
        self.disable8_9 = ttk.Checkbutton(labelframe1)
        self.disableval8_9 = tk.BooleanVar()
        self.disable8_9.configure(variable=self.disableval8_9)
        self.disable8_9.grid(column=9, row=8)
        self.disable8_9.configure(command=self.chkDisable_click)
        self.disable8_10 = ttk.Checkbutton(labelframe1)
        self.disableval8_10 = tk.BooleanVar()
        self.disable8_10.configure(variable=self.disableval8_10)
        self.disable8_10.grid(column=10, row=8)
        self.disable8_10.configure(command=self.chkDisable_click)
        self.disable8_11 = ttk.Checkbutton(labelframe1)
        self.disableval8_11 = tk.BooleanVar()
        self.disable8_11.configure(variable=self.disableval8_11)
        self.disable8_11.grid(column=11, row=8)
        self.disable8_11.configure(command=self.chkDisable_click)
        self.disable8_12 = ttk.Checkbutton(labelframe1)
        self.disableval8_12 = tk.BooleanVar()
        self.disable8_12.configure(variable=self.disableval8_12)
        self.disable8_12.grid(column=12, row=8)
        self.disable8_12.configure(command=self.chkDisable_click)
        self.disable8_13 = ttk.Checkbutton(labelframe1)
        self.disableval8_13 = tk.BooleanVar()
        self.disable8_13.configure(variable=self.disableval8_13)
        self.disable8_13.grid(column=13, row=8)
        self.disable8_13.configure(command=self.chkDisable_click)
        self.disable8_14 = ttk.Checkbutton(labelframe1)
        self.disableval8_14 = tk.BooleanVar()
        self.disable8_14.configure(variable=self.disableval8_14)
        self.disable8_14.grid(column=14, row=8)
        self.disable8_14.configure(command=self.chkDisable_click)
        self.disable8_15 = ttk.Checkbutton(labelframe1)
        self.disableval8_15 = tk.BooleanVar()
        self.disable8_15.configure(variable=self.disableval8_15)
        self.disable8_15.grid(column=15, row=8)
        self.disable8_15.configure(command=self.chkDisable_click)
        self.disable8_16 = ttk.Checkbutton(labelframe1)
        self.disableval8_16 = tk.BooleanVar()
        self.disable8_16.configure(variable=self.disableval8_16)
        self.disable8_16.grid(column=16, row=8)
        self.disable8_16.configure(command=self.chkDisable_click)
        labelframe1.grid(column=0, columnspan=2, row=0)
        labelframe5 = ttk.Labelframe(frame2)
        labelframe5.configure(height=200, text='Debounce (ms)', width=200)
        label50 = ttk.Label(labelframe5)
        label50.configure(text='Click')
        label50.grid(column=0, row=0)
        self.txtDebounceClickVal = ttk.Entry(labelframe5)
        self.debounce_click = tk.IntVar()
        self.txtDebounceClickVal.configure(textvariable=self.debounce_click)
        self.txtDebounceClickVal.grid(column=1, row=0)
        label52 = ttk.Label(labelframe5)
        label52.configure(text='Boom')
        label52.grid(column=0, row=1)
        self.txtDebounceBoomVal = ttk.Entry(labelframe5)
        self.debounce_boom = tk.IntVar()
        self.txtDebounceBoomVal.configure(textvariable=self.debounce_boom)
        self.txtDebounceBoomVal.grid(column=1, row=1)
        labelframe5.grid(column=0, columnspan=2, pady=10, row=1)
        self.btnSaveConfig = ttk.Button(frame2)
        self.btnSaveConfig.configure(text='Save')
        self.btnSaveConfig.grid(column=1, pady=10, row=3)
        self.btnSaveConfig.configure(command=self.save_config)
        self.chkResetAfterBoom = ttk.Checkbutton(frame2)
        self.reset_after_boom = tk.BooleanVar()
        self.chkResetAfterBoom.configure(
            text='Mines can go boom more than once',
            variable=self.reset_after_boom)
        self.chkResetAfterBoom.grid(column=0, columnspan=2, row=2)
        self.btnLoadConfig = ttk.Button(frame2)
        self.btnLoadConfig.configure(text='Restore from last save')
        self.btnLoadConfig.grid(column=0, row=3)
        self.btnLoadConfig.configure(command=self.reload_config)
        frame2.grid(column=0, row=0)
        notebook1.add(frame2, text='Config')
        notebook1.pack(side="top")

        # Main widget
        self.mainwindow = self.minewindow

    def run(self):
        self.mainwindow.mainloop()

    def go_click(self):
        play_click_sound()

    def go_boom(self):
        play_boom_sound()

    def reset_mine_states(self):
        init_mine_states()

    def chkDisable_click(self):
        pass

    def save_config(self):
        save_config_to_file(self)

    def reload_config(self):
        load_config_from_file(self)


mine_states = None

# Handle window closing
closeRequest = False

def on_closing():
    global closeRequest
    closeRequest = True
    print("close request received")

# init mine state matrix (list of lists)
def init_mine_states():
    global mine_states
    mine_states = []
    for card_id in range(8):
        row = []
        for ch_id in range(16):
            row.append(msm.Mine())
        mine_states.append(row)

#https://stackoverflow.com/questions/33608280/convert-4-bit-integer-into-boolean-list
def int_to_bool_list(num):
    return [bool(num & (1<<n)) for n in range(16)]

def scan_inputs(app):

    scan_result = []

    for card_id in range(8):
        scan_result.append(int_to_bool_list(ic.readAll(card_id)))

    # scan_result should be a list of 8 lists with 8 bools in each list

    # iterate through results. card_id and ch_id are zero-based counters
    sound_to_play = 0
    for card_id,card_vals in enumerate(scan_result):
        for ch_id,ch_val in enumerate(card_vals):
            # Show current states in checkboxes
            getattr(app, "stateval{}_{}".format(card_id+1,ch_id+1)).set(ch_val)

            # Check disabled state
            disabled = getattr(app, "disableval{}_{}".format(card_id+1,ch_id+1)).get()

            res = mine_states[card_id][ch_id].inputReading(ch_val)

            if res.value > sound_to_play:
                sound_to_play = res.value     # play the worst sound we find

            #print(sound_to_play)

    # PLAY SOUND sound_to_play
    if sound_to_play == 1:
        play_click_sound()
    elif sound_to_play == 2:
        play_boom_sound()
    else:
        pass


def save_config_to_file(app: MinefieldApp):

    # Load disable checkboxes into a list
    disabled_ch = []
    for card_id in range(8):
        row = []
        for ch_id in range(16):
            row.append(getattr(app, "disableval{}_{}".format(card_id+1,ch_id+1)).get())
        disabled_ch.append(row)
    
    debounce_click = app.txtDebounceClickVal.get()
    debounce_boom = app.txtDebounceBoomVal.get()
    reset_after_boom = app.reset_after_boom.get()

    try:
        with open("minefield.settings", 'wb') as f:
            pickle.dump((disabled_ch, debounce_click, debounce_boom, reset_after_boom), f, protocol=pickle.HIGHEST_PROTOCOL)

        # Load disabled channels into checkboxes
        for card_id,card_vals in enumerate(disabled_ch):
            for ch_id,ch_val in enumerate(card_vals):
                getattr(app, "disableval{}_{}".format(card_id+1,ch_id+1)).set(ch_val)

        app.debounce_click.set(debounce_click)
        app.debounce_boom.set(debounce_boom)

        app.reset_after_boom.set(reset_after_boom)
        
    except:
        print("Error saving config!")



def load_config_from_file(app:MinefieldApp):

    def restore_disables():
        for card_id in range(8):
            # Set all channel 1s by default
            getattr(app, "disableval{}_{}".format(card_id+1,1)).set(True)
            for ch_id in range(1,16):
                getattr(app, "disableval{}_{}".format(card_id+1,ch_id+1)).set(False)

    def restore_click():
        app.debounce_click.set(500)

    def restore_boom():
        app.debounce_boom.set(500)

    def restore_reset():
        app.reset_after_boom.set(True)


    try:
        with open("minefield.settings", 'rb') as f:
            disabled_ch, debounce_click, debounce_boom, reset_after_boom = pickle.load(f)

        # Load disabled channels into checkboxes
        for card_id,card_vals in enumerate(disabled_ch):
            for ch_id,ch_val in enumerate(card_vals):
                getattr(app, "disableval{}_{}".format(card_id+1,ch_id+1)).set(ch_val)

        try:
            app.debounce_click.set(int(debounce_click))
        except:
            restore_click()

        try:
            app.debounce_boom.set(int(debounce_boom))
        except:
            restore_boom()

        try:
            app.reset_after_boom.set(reset_after_boom)
        except:
            restore_reset()

    except:
        restore_disables()
        restore_click()
        restore_boom()
        restore_reset()



# Custom handler loop to accomodate game logic
if __name__ == "__main__":
    init_mine_states()

    app = MinefieldApp()
    app.minewindow.protocol("WM_DELETE_WINDOW", on_closing)
    load_config_from_file(app)

    while (closeRequest==False):
        app.minewindow.update()
        scan_inputs(app)